### ISSUE TITLE
Evaluate the logging of SemeioScript

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#104]
In #99 `SemeioScript` adds a handler to the root logger to ensure that log statements is propagated via the reporter to the appropriate place. However, currently this most likely have the side effect that log statements from the ERT application will end up also in the workflow log. This should be avoided. At the same time we want log-statements from the workflow and the libraries it is utilising to end up in the same place.

We can probably use the thread id to make a filter that can be appended to the handler. But hopefully there is a more robust and elegant solution.

**Comment by jondequinor** [comment]
From semeio's point of view, I can't find an elegant solution other than what you propose.

https://github.com/equinor/semeio/pull/161

On the other hand, threading is an inherent part of `logging`, so maybe it's not inelegant after all.
