### ISSUE TITLE
Fetch `alpha` and `std_ cutoff`

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#105]
The ACO (and SC) job should use the `alpha` and `std_cutoff` values used by ERT, unless something else is configured explicitly.

As a first step it is probably sufficient to implement this for ACO and then let SC behave similarly after #108

**Comment by oysteoh** [comment]
@oyvindeide this one is ready to be closed yes? or do you expect more pr's to connect?

**Comment by oyvindeide** [comment]
Yes, I just forgot to name it in the PR - thanks for reminding.
