### ISSUE TITLE
[GENDATA_RFT] Extracts saturations

### ISSUE THREAD

**Issue by berland** [equinor/semeio#106]
Gendata_rft can be extended to also extract saturations from the same `.RFT` file, this functionality has existed in a fork `gendata_rftsat` of the original `gendata_rft`, and is in use by several assets.

Similar request in https://github.com/equinor/ecl2df/issues/41

**Comment by berland** [comment]
https://github.com/equinor/subscript/issues/54

**Comment by oyvindeide** [comment]
Closed in #154
