### ISSUE TITLE
Unite the schema's

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#108]
Currently there is no overlap between the schema's of the spearman job and the black box job implemented in #70. The same holds for the correlated observation scaling.

We should investigate whether default values and schema's can be fetched from the corresponding jobs and utilised in the black box job of https://github.com/equinor/semeio/milestone/1.

**Comment by jondequinor** [comment]
I don't think there's a good way to unite the schemas. Having SC and MP concern themselves with the configuration of COS seems to me to break good encapsulation. A config is a good way for a _user_ to interface with a job, but I don't think it's a good way for a job to interface with another job. In that sense, the configuration schema and validation are implementation details. I _think_ this is what is described in https://github.com/equinor/semeio/issues/75? @markusdregi maybe you can confirm/deny.

So I will create the `ScalingJobConfig` contract between COS and SC|MP.

**Comment by markusdregi** [comment]
I agree 👍 It could even be discussed whether all the jobs should be kept in the end...

**Comment by jondequinor** [comment]
So, creating a configuration class in COS would then either accept a user configuration, or pertinent keyword arguments in an initializer. The user configuration would be passed to the initializer via a translation.

Would you say this breaks with the/your philosophy of Configsuite; that 

> I would prefer that the world view of the executor of the configuration and the user is the same and that whatever needs to be processed or translated in-between is as transparent as possible.

I will argue it does not. Currently, COS will rewrite the user provided configuration before validation—breaking with the philosophy. In the case where we do a translation before the initializer, the user provided configuration is left untouched.

The question remains, what do you mean by _transparent_?

**Comment by markusdregi** [comment]
What I mean by *transparent* is to have a common ground configuration between the application and the user for which they can both refer to. In particular, the user starts out with a configuration of the behaviour it expects. This is passed to the application which then loads, interprets and then executes the configured behaviour. In my opinion validation makes the most sense on the interpreted configuration as it is then in an executable condition. However, feedback to the user based on the interpreted configuration only makes sense if the interpretation process itself is transparent to the user. As otherwise one quickly ends up in a situation where the user is talking about apples and the application about oranges. This is what I meant by transparency; that the interpretation process of the configuration before it is executed is transparent to the user to ensure a common ground of communication. `configsuite` tries to address this by supporting a schema language that can describe the interpretation, for which one later can fetch both documentation of the process and the process itself. I agree that COS currently violates this philosophy by among others expanding keywords after extracting the data from the schema.

However, I think that no matter whether you agree with the above philosophy, the suggested effort by @jondequinor does not interfere with this. Furthermore, it sounds like we all agree the unification of the schemas is probably not a good idea. So what is it then we would like to achieve? And should we address it now?

**Comment by oyvindeide** [comment]
Should we close this issue? We have discussed removing the other entry points (they could be added as options to the `MISFIT_PREPROCESSOR`) which makes this issue irrelevant.

**Comment by markusdregi** [comment]
I vote yes, and take action accordingly 😬
