### ISSUE TITLE
Spearman calculation failing with seismic data

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#11]
Spearman calculation failing with "The condensed distance matrix must contain only finite values", probably because the input matrix contains 0 or NaN values. The scipy.fcluster is most likely where it is failing.

**Comment by xjules** [comment]
Either the NaN columns are removed or we use another distance metric for those columns, e.g.:
```python
def our_dst(a, b):
   s = np.sum(np.dot(a-b,a-b))
   return 1/(1+s*s)
```
giving us close to 0 values (no-corr) or 1 (corr)

**Comment by oyvindeide** [comment]
> Either the NaN columns are removed or we use another distance metric for those columns, e.g.:
> 
> ```python
> def our_dst(a, b):
>    s = np.sum(np.dot(a-b,a-b))
>    return 1/(1+s*s)
> ```
> 
> giving us close to 0 values (no-corr) or 1 (corr)

Good suggestion, seems the consensus from the users is that filtering the data upfront is the preferred method, so have implemented that here.
