### ISSUE TITLE
[GENDATA_RFT] Include observed values

### ISSUE THREAD

**Issue by berland** [equinor/semeio#116]
Users request inclusion of observed values in the CSV export from `gendata_rft.py`. 

A quick glance indicates that this can be handled as meta-information in the Trajectory class, by also reading the text files `<well_name>.obs`.

Issues #91 and #106 together with this constitutes an upgrade of gendata_rft into something more than its original intent (providing the individual text files input to the ert `GENDATA` keyword). 

These steps should be seen as a step towards a major rewrite of how RFT data is handled in assisted history match. The assumption for the future solution is that CSV files (or dataframes) holds the data used in the process.

**Comment by berland** [comment]
The observation files are only present in CONFIG_PATH.

It should be considered whether the `*.obs` files should be copied to the RUN_PATH by ert/libres for semeio to pick it up.

**Comment by oyvindeide** [comment]
Dont think it is very viable to copy the files over, as they are in the domain of `ert` and should be served up through an API instead. That is not yet the case, but the new storage solution should make that easier.

**Comment by markusdregi** [comment]
Could you please elaborate on what it is you want to achieve? Why is it that one would want the observed values in the CSV-export from `gendata_rft.py`? The current rft implementation definitively needs some love, but I think it would benefit vastly from continuing the storage / data API work first...

**Comment by berland** [comment]
The Webviz visualization plugin wants to plot simulated and observed RFT values, and is as we speak building support for the CSV-export from GENDATA_RFT. Currently there is no simple way for this webviz plugin to get hold of the observed data, and users need to provide a custom text-file with this information for the plugin to work.

**Comment by markusdregi** [comment]
I think copying observed data to each of the realisations to be able to export them into csv-files so that they can be plotted by a centralised instance is not a good architectural direction for this. Observations are exposed via the data API of ERT. It is only experimental for now, but that will be resolved soon and in the meantime the functionality can be implemented and tested on non-classified data :)

**Comment by berland** [comment]
Thanks. API it is then. Is it ok for the gendata_rft job to access the API and inject the value (or the calculated mistfit) into the dataframe/CSV, or do we see a reason to keep any observation data completely out of any data structures relating to single realizations?

**Comment by markusdregi** [comment]
Personally I think that would be in the wrong direction as it entails copying knowledge about the experiment into the runpath to be able to inject it into a CSV for later to do data loading for the experiment. Is there any reason for why Webviz cannot use the API directly?

**Comment by asnyv** [comment]
@markusdregi Sorry that I am a bit late here... But mainly to not depend on the existence of ERT storage for a run until the new API is in place. Quite common that users delete storage, and we would like to be able to compare with historical runs, therefore nice to have some information on the experiment stored with the rest of the data.

But you could of course argue that a solution that isn't supposed to be the long term way to do it, shouldn't be in semeio.

**Comment by markusdregi** [comment]
@asnyv Sorry for being even more late with the reply :palm_tree: 

A new solution for ERT storage is actively being developed to avoid the need for deleting storage and loosing data. I think we should continue down that path to fix this issue :)

**Comment by berland** [comment]
As a temporary solution for the webviz need of merged data, a script that does only the merging part is in progress for subscript: https://github.com/equinor/subscript/pull/195
