### ISSUE TITLE
[MISFIT_PREPROCESSOR] Handle Configsuite Breaking Change

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/semeio#118]
The `0.6.0` of ConfigSuite brings the possibility of allowing the user to specify `None` as a valid input and also providing a `Default` value for a basic type. This change came with additional keywords `Default` and `AllowNone`, the latter must explicitly be set if the keyword is not `Required`.

The `Required` keyword is furthermore deprecated as it can be deduced given the value of `Default` and `AllowNone`:

https://configsuite.readthedocs.io/en/latest/user_guide/deprecated_behaviour.html

**Comment by oyvindeide** [comment]
This seems to already be valid as there is no use of `Required`
