### ISSUE TITLE
[DESIGN_KW] Support spaces in values

### ISSUE THREAD

**Issue by berland** [equinor/semeio#119]
Users sometimes need spaces in strings as values when using DESIGN_KW. 

This would require changes to `design2params.py` as well.

**Comment by berland** [comment]
A change on this should be synchronized with
* design2params in semeio
* params2csv in subscript
* fmudesign in fmu-tools

**Comment by berland** [comment]
fmu-ensemble and params2csv already supports spaces if they are quoted. The command to parse `parameters.txt` is there `pandas.read_csv(sep="\s+")` which will allow
```
FOO "1 2 3"
```
in `parameters.txt`. `fmu-ensemble` also adds `usecols=[0,1]` to the `read_csv` options, to make it ignore and not file unquoted values with spaces.

**Comment by havarhal** [comment]
What about strings including both letters and numbers? I tried with 1 JAN 2027 without quotes and got an error saying that it could not be parsed into a value.

**Comment by tralsos** [comment]
Hm, I tried now with both a dist (discrete) and a scenario sensitivity, and with 1 JAN 2027. This worked for me. Could you provide me a spreadsheet to test ?

**Comment by havarhal** [comment]
It failed in DESIGN_KW
the magic strings are not replaced

**Comment by berland** [comment]
Correct. Spaces in values are currently supported by DESIGN_KW, even though fmudesign can emit it.

**Comment by tralsos** [comment]
You mean not supported ?
