### ISSUE TITLE
[COS] Reporter overwriting previous values

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#120]
The [COS] job can typically be run several times back to back, and currently the reported values are overwritten each time, should be append perhaps?

**Comment by markusdregi** [comment]
But do we have a good way of appending? We could of course put them in a list expanding each time a new element is published, but that will put some more burden on the consumer side. Also, we should keep in mind that this data is not meant to reside on disk for long :)

**Comment by oyvindeide** [comment]
Maybe not, and maybe it is a won't fix. However the usefulness is limited in the current form.

**Comment by markusdregi** [comment]
We should at least try to mitigate values being overwritten.
