### ISSUE TITLE
Reports end up as a case

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#136]
The reporter puts the reports in a folder called `reports` within `ENSPATH`. After a run, a new case named `reports` shows up, which is not exactly as it is supposed to be. Let us see if we can either change the name (like making it a hidden folder) to avoid storage picking it up. If not, we'll have to find a different place to put the reports...

Steps to reproduce:
- Fetch the poly case
- Load and hook `MISFIT_PREPROCESSOR`
- Run ES
- Inspect the cases in the GUI

**Comment by lars-petter-hauge** [comment]
Verified that renaming to `.reports` will mitigate the bug. Unsure if that's the optimal solution though. If the content of `.reports` eventually will only go to the new ert-storage, then I am satisfied with the temporary solution (although I am not sure if there are other consequences of adding anything to the `storage` folder).

**Comment by sondreso** [comment]
Resolved by https://github.com/equinor/semeio/pull/169
