### ISSUE TITLE
[design2params]  TRUE is mapped to True

### ISSUE THREAD

**Issue by berland** [equinor/semeio#166]
A design matrix cell value with the string `TRUE`, is mapped into `True` in  `parameters.txt`.

This conflicts with the Py2 behaviour, and crashes some FMU workflows.

Credit: ilor

**Comment by berland** [comment]
The culprit is  `pd.read_excel()` which converts to dtype `bool` when possible.

**Comment by oyvindeide** [comment]
Solved in #167
