### ISSUE TITLE
[GENDATA_RFT]: Add optional directory for outputted files.

### ISSUE THREAD

**Issue by berland** [equinor/semeio#174]
User request to be able to have all the files written to a specified directory, and not directly in RUNPATH.

Number of files written by `gendata_rft` is 1 and up to theoretically hundreds, which clutter up.

This could be implemented as an option with default `.`. 

The job should probably the assume the directory is there  already.

(assuming that `GENDATA` is happy loading files from relative paths)

@rnyb, @erlid

**Comment by markusdregi** [comment]
This is the function that write the files: https://github.com/equinor/semeio/blob/1dcc19e515b94ac0c9225c100d7e46f86beb248d/semeio/jobs/rft/gendata_rft.py#L7

I support the alternative of defaulting to `.` 👍
