### ISSUE TITLE
Generate documentation in CI pipeline

### ISSUE THREAD

**Issue by berland** [equinor/semeio#175]
The semeio jobs generate documentation from argparse and RST files(?), but this is not checked for syntax errors and alike in the CI pipeline.

**Comment by oyvindeide** [comment]
Very much support adding checks to the documentation, there is something for some of them, for example: 
```
@pytest.mark.parametrize("input_rst", [cos._DESCRIPTION, cos._EXAMPLES])
def test_valid_rst(input_rst):
    """
    Check that the documentation passed through the plugin system is
    valid rst
    """
    assert not list(rstcheck.check(input_rst))
```
in https://github.com/equinor/semeio/blob/9e691042a1c1b91510e0e14e6232e9cb43a9e65f/tests/jobs/correlated_observations_scaling/unit/test_examples.py#L34

Not perfect, but could serve as a starting point for other tests.

**Comment by oyvindeide** [comment]
I will close this as stable, but we should keep it it mind when anything that passes on documentation to `ert` is touched.
