### ISSUE TITLE
Default linkage for misfit preprocessor, spearman_correlation option

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/semeio#183]
The current default for linkage (single linkage) has been observed to induce when user have tested it. Should be changed for the misfit preprocessor and or spearman correlation jobs.

**Comment by oyvindeide** [comment]
Based on testing from we should update the default option for the `spearman_correlation` option in the misfit preprocessor, we could also consider updating the default in the `spearman` job. 

Reach out to testers to find which option has worked the best as a default option.

**Comment by tralsos** [comment]
Based on the testing we did it seems like having default setting for clustering method  "maxclust" and default linking method "average" works well for the real data observation sets we were using. There were problems with using the single linkage, probably due to smoothness in maps etc.

**Comment by oyvindeide** [comment]
> Based on the testing we did it seems like having default setting for clustering method "maxclust" and default linking method "average" works well for the real data observation sets we were using. There were problems with using the single linkage, probably due to smoothness in maps etc.

I did not update the default clustering method, because I cant find a good way to define a default value for `maxclust` as the data sets are so varied (you could make the same argument for `inconsistent`, but it is slightly less opinionated in my mind).
