### ISSUE TITLE
Overburden timeshift job: resolve vintage order in geertsma_ts

### ISSUE THREAD

**Issue by xjules** [equinor/semeio#189]
In `geertsma_ts` method in `ots.py` the vintage order is swapped, ie.:
```python
self.add_survey("base", monitor)
self.add_survey("monitor", base)
```
This needs to be resolved by either keeping it as is by providing a reasonable explanation and tests, or swapped as there is already a parameter `self._convention`, which changes sign if the order was reversed.

**Comment by markusdregi** [comment]
I think @kjellkongsvik has months of experience flipping the sign 😂

**Comment by xjules** [comment]
> I think @kjellkongsvik has months of experience flipping the sign 😂

I've heard the rumors :)

**Comment by oyvindeide** [comment]
Do we have any information that can resolve this? @xjules, @lars-petter-hauge?

**Comment by lars-petter-hauge** [comment]
I believe we asked research about this and they did say that they thought it could be a bug:

> I agree with you, since there is a free parameter defining the convention, the code does not need to account for reversed polarity in any other ways…. Are you able to test if all models give the same convention for the output time shifts? (If this is not the case, I start to believe there is an error in the code).

And:

> I think you are right! There might be a bug in the code on applying the convention and switch the data both (-1 x -1=1 to me).

We have not answered the question though

**Comment by berland** [comment]
@xjules , are there any updates here or should we close due to lack of activity?

**Comment by xjules** [comment]
No updates. Let's close it then.
