### ISSUE TITLE
OTS config segfaulting

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#203]
If `extract_ots_context` is not mocked the test segfaults with: `test_ots_config.py::test_invalid_config Fatal Python error: Segmentation fault`

Steps to reproduce:

Remove the mocking of `extract_ots_context` (this _should_ only raise a ConfigurationError) and run the test:

https://github.com/equinor/semeio/blob/66f6ae542c79a2c7ad9b6cadb93a2f39fa66cabe/tests/jobs/overburden_timeshift/test_ots_config.py#L42

**Comment by lars-petter-hauge** [comment]
see also: https://github.com/equinor/ecl/issues/786
