### ISSUE TITLE
Calling scaling job from spearman job failing

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#23]
Calling the scaling job from the spearman correlation job can fail with `"The script 'SpearmanCorrelationJob' caused an error while running: Empty dataset, all data has been filtered out' `, this is most likely caused by filtering both ensemble mean and towards observation mean in scaling job, and only ensemble mean in spearman correlation. This will happen more frequently because we can have clusters with a single data point, increasing the chance that the filtering will remove all the data. Should probably add a check to: 
```
def _run_scaling(facade, job_configs):
    for job in job_configs:
        scaling_job(facade, job)
```
to skip if the cluster size is 1 (or the scaling job should skip if only one member?)

**Comment by jondequinor** [comment]
In addition to the cluster check, we should skip the scaling_job should it fail with that specific data set empty exception.
