### ISSUE TITLE
[design2params] Warn, fail or fix trailing whitespace in parameter names.

### ISSUE THREAD

**Issue by berland** [equinor/semeio#243]
If a user accidentally includes trailing whitespace in the parameter names in the design matrix excel sheet, `design_kw` will fail with (correct) error messages that the parameter does not exist. 

`2020-10-22 13:07:13,236 - semeio.jobs.design_kw.design_kw - ERROR - <H10_START> not found in design matrix`

This is non-trivial for users to notice, as the parameter seemingly exists in the Excel gui.

On disk, the problem can be identified by looking in `parameters.txt`:

```
$ grep "H10_START" parameters.txt
"H10_START " 4350
```
where the trailing space is evident. 

This can be solved by one of:
1. Disallow trailing whitespace, and error hard
2. Give warning from design2params (but these warnings are not likely to be discovered, as the failure occurs potentially much later in `design_kw`)
3. Strip trailing whitespace from parameter names in design matrix (and in defaultssheet)
4. Modify design_kw to look for this specific situation, and then pick the parameter with the trailing whitespace (this sounds ugly)
5. Do nothing.

Trailing whitespace in cell values should be conserved, as it is a feature that may already be in use.

**Comment by berland** [comment]
If noone can come up with a use-case for a trailing white-space in a parameter name, my vote goes towards 1.

**Comment by markusdregi** [comment]
I'm also in favor of 1 :+1:

**Comment by oyvindeide** [comment]
Solved by: https://github.com/equinor/semeio/pull/244
