### ISSUE TITLE
Dump the stea response json

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#27]
Today the stea job dumps the response json in a peculiar format tailored to ERT's dataformat. We should instead dump the richer format and let the user further process that to their needs.

I think this has been requested previously by @berland

**Comment by berland** [comment]
Yes, see https://github.com/equinor/ert-statoil/issues/166#issuecomment-567501209

**Comment by oyvindeide** [comment]
This is solved by dumping the full response in addition to the existing format and deprecating the existing format.
