### ISSUE TITLE
Have DESIGN_KW create folder if it does not exist

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#276]
Currently, the `DESIGN_KW` will fail if the folder it is to be dumped in does not exist. Should perhaps be more like the behavior of `GEN_KW` that would then create the folder.

See https://www.yammer.com/statoil.com/#/threads/show?threadId=974654574 for internal discussion.

**Comment by oyvindeide** [comment]
I will close this as I am not convinced this feature should be implemented, and it should be the responsibility of the user to create the folder (or `ert` might take that responsibility with a `resources` keyword or similar). Feel free to reopen if you disagree.
