### ISSUE TITLE
No logging.INFO messages from forward models in stdout files in ert

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#300]
**Describe the bug**
Despite a log handler that should pass on `INFO` level to `stdout`, no `INFO` messages are available from forward model jobs.

**To Reproduce**
1. Create a forward model job, for example name `log_test.py`: 
  ```
import logging
logger = logging.getLogger(__name__)

def main():
    logger.info("Starting")
  ```

2. Add `main` from this file to `console_scripts` in `setup.py`
3. Add a `ert` config (for example `MY_LOG_JOB` in `semeio/jobs/config_jobs`:
  ```
EXECUTABLE     log_job
  ```
4. Pip install `ert`
5. Run `ert` with this forward model

**Expected behavior**
Expect "Starting" to be present in `MY_LOG_JOB.stdout` in the `ert` run.

**Comment by berland** [comment]
A fix (with tests) on this is probably blocked by #306

**Comment by berland** [comment]
Some background: https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout

**Comment by berland** [comment]
See also https://github.com/equinor/subscript/pull/333

**Comment by lars-petter-hauge** [comment]
`Logger` objects will correctly pass `LogRecords` to their parent, and we have set the handlers on the `semeio` module (root logger), thus any `LogRecord` from for instance in this case `semeio.jobs.scripts.log_job` will progress to root logger as long as it is not stopped by a filter. 

The reason content from `logger.info` does not reach the `stdout` of ert is that the logger instance itself has not been given a log level (neither in `semeio`, nor in the job), and thus is set to default `WARNING`. The level of the logger is checked prior to sending the `LogRecord` to the `Handler`. Setting the log level in the `log_test.py` to `INFO` will allow `LogRecords` from `logger.info` in a job to reach the root logger. I was under the impression that the level of a logger, unless explicitly set, is only inherited from parents, and hence it would be necessary to also set the log level for the root logger to `INFO`. Doing a test however demonstrated that it was only necessary to set it on the job logger.

Any `LogRecord`s using `loglevel.DEBUG` will however not reach `stdout`, as the `StreamHandle` has a loglevel set to `INFO`. We should consider setting the `StreamHandle` to `DEBUG`, to allow `LogRecords` passed from jobs with `DEBUG` level be processed by the handler. Each jobs logger level will still need to be set to `DEBUG` in order for `LogRecords` to be passed on, so we won't see any additional messages unless that is done.

I also notice that most of our jobs does not set loglevel in their jobs, we might have thought that simply setting the `StreamHandler` would suffice. The log level will therefore be the default; `WARNING`, and `LogRecords` of lower level will never reach root logger. Most jobs does not allow for the level to be set to anything else either, we should have it configurable (allowing users to set e.g. `DEBUG`).

A possibility would be to set the log level on the root logger, and hence all jobs will inherit said level (unless the job itself explicitly sets it). I would prefer leaving root logger as is though, and rather make the jobs themselves set the level (given that the observation I had earlier is correct, and that a default `WARNING` on the root logger does not stop `LogRecord`s of lower levels to reach the streamhandler.

See https://docs.python.org/3/howto/logging.html#logging-advanced-tutorial for more information

**Comment by oyvindeide** [comment]
Setting log level to `INFO` is probably ok as long at it is done at the job level, messing with the `root` logger we should do with care so we only do it in the entry point of the jobs, and never in the workflows (or on init).

**Comment by berland** [comment]
This issue should be closeable. Default loglevels for semeio when run from `ert` can be controlled in the file https://github.com/equinor/ert/blob/main/src/ert/logging/logger.conf
