### ISSUE TITLE
ERT does not run on OSX for semeio forward models

### ISSUE THREAD

**Issue by berland** [equinor/semeio#306]
**Describe the bug**
Semeio CI on github actions cannot run ERT on OSX due to case insensitive file system

**To Reproduce**
Run #304 on MacOSX

**Expected behavior**
Tests to pass

**Additional context**

https://github.com/equinor/semeio/pull/304#issuecomment-789533300

**Comment by oyvindeide** [comment]
There is this workaround for your PR, but does nothing to fix the underlying problem: https://github.com/equinor/semeio/blob/15565c26e02c791954468c8a9982cadd45ffb0a5/tests/test_ert_integration.py#L24

**Comment by berland** [comment]
I am fine with both a workaround and a proper fix.
