### ISSUE TITLE
STEA forward model & ecl-case 

### ISSUE THREAD

**Issue by CecilieOtterlei** [equinor/semeio#310]
The STEA forward model doesn't pick up the realisation number for the ECLBASE in the ecl-case automatically. Currently a workaround symlinking the ECLBASE to a general name, has to be used. 
![image](https://user-images.githubusercontent.com/61050747/111625117-ca3da000-87ec-11eb-989f-50a4a77b57b6.png)
![image](https://user-images.githubusercontent.com/61050747/111625200-e04b6080-87ec-11eb-8f71-d530637edb80.png)
![image](https://user-images.githubusercontent.com/61050747/111625292-fa853e80-87ec-11eb-8e69-35cd97fe12a1.png)

**Comment by berland** [comment]
The forward model should have an argument `ECLBASE` (unfortunately, this is named `ECLROOT`/`ECLBASE`/`DATAFILE`  in similar forward models, but we should probably stick to reusing the ERT keyword ECLBASE here.

ECLBASE should have a default that makes it ignored (to pick it up from  yml instead), and if it is non-default in forward model, it should override the yml-setting.

**Comment by oyvindeide** [comment]
Would suggest mirroring the config, and have `ECL_CASE` instead of `ECLBASE` to avoid confusion. But there. might be confusion anyway...
