### ISSUE TITLE
Bringing REPLACE back

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#312]
The `REPLACE` job was abandoned some time ago, but appears too still have some usage for very small replacement tasks. Due to this it is suggested by @eivindsm to reintroduce it. However, I suggest that instead of reintroducing the previous one we make an alternative powered by `sed`.

Something along the lines of
```
EXECUTABLE sed
ARGLIST -i `s/<FROM>/<TO>/g` <FILE>
```
should be sufficient.

As this is really hard to unit test, I suggest that we add the workflow to the HM tutorial version that does integration testing for most of the jobs in libres + semeio

**Comment by sondreso** [comment]
Ref testing: https://github.com/equinor/semeio/blob/master/tests/jobs/nosim/test_nosim.py

**Comment by oyvindeide** [comment]
@markusdregi is this still something we should implement?

**Comment by markusdregi** [comment]
I think the use case still makes sense and it should be rather low effort to actually execute upon this? My main scepticism is that we would not have any users requesting the feature as of now...

Perhaps we could do some investigation and if we find some users willing to describe their usage and test a potential solution, then we act upon it. If not, we close it...

**Comment by oyvindeide** [comment]
Sounds like a reasonable approach, but how would we go about investigating?

**Comment by markusdregi** [comment]
Initiated a request. If no users come up, we can close this by the end of January 👍🏻

**Comment by markusdregi** [comment]
There seems to be interest for a replace job :) Users for testing can be found here: https://equinor.slack.com/archives/CDPJULWR4/p1641372040116600?thread_ts=1640178281.098100&cid=CDPJULWR4

**Comment by asnyv** [comment]
Suggestion: Would it be an idea to use a more explicit name, like e.g. `REPLACE_STRING`?

**Comment by markusdregi** [comment]
I don't mind @asnyv :)

**Comment by ManInFez** [comment]
sed was apparently not sufficient, reopening issue
