### ISSUE TITLE
Make internal workflow for a localisation job

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/semeio#314]
Currently localisation, the ability to explicitly state which observations a parameter should be updated with respect to, can be defined in an internal workflow, following the example given in the documentation: https://github.com/equinor/ert/blob/master/docs/rst/manual/advanced/api.rst

Ert will otherwise update all parameters with respect to all observation irrespective if they are relevant or not.

We want to create a workflow that would allow the user to use a different interface (e.g. a config file) instead of writing their own python script. There have also been new features added (see https://github.com/equinor/libres/issues/1070), which allows us to have the importance of the observation in an update be a function of e.g. distance to the parameter. This workflow should also utilise the new functionality.

Provided user stories:

**Use Story:**
I have Observations related to a well. We have some scalar parameters, should they be affected based on the observation or not?

Scenario: All the wells in the northern parts of the field should affect only parameters in the northern part of the field.

The weighting is either 1 or 0.

**Use Story:**
I have a surface or a 3D field where parameters are updated. I would like the parameters to be updated with a weighting (decay function) given the distance to a well (observation related to a well).

**Additional comments:**

> Instead of re-configuring everything (which is the case today), I would like to disable certain obs-param set

Questions:
 - What happens to the parameter / observation set not described in the configuration?

**Comment by oddvarlia** [comment]
With 	obs_data = local_config.copyObsData("ALL_OBS", "All_except_obs1") it is possible to create a copy of all obs data set and this can be used to take out some obs nodes and then correlate those again to selected model parameter nodes. By adding the reduced obs set to all model parameter nodes, it is possible to make a workflow where the user first start will all obs correlated to all model parameters and then gradually take out some obs or modify some obs nodes correlation to some selected model parameter nodes. A remaining question is: Does there exist something like ALL_MODEL_PARAMETERS analogous to ALL_OBS ?

**Comment by oyvindeide** [comment]
This has now been implemented.
