### ISSUE TITLE
Change default output directory name for workflow utility SemeioScript

### ISSUE THREAD

**Issue by mareco701** [equinor/semeio#321]
https://github.com/equinor/semeio/blob/3605d379b4af1f4f221050d93a2038ac5606ad46/semeio/communication/semeio_script.py#L81
Having the results ert/output/storage/reports/currentcasename/workflow_name is not ideal since we need to be able to relate them to a case (ert config name) and avoid overwritting if the workflow is run from different ert config files. Could it be changed to  ert/output/storage/reports/ertconfigname/currentcasename/workflow_name ? i.e. change base_dir to be Enspath for example.

**Comment by oyvindeide** [comment]
@markusdregi you were part of making the original implementation, do you remember the original rational behind it? Also on overwriting, I remember us discussing it, but cant quite remember the details.

**Comment by oyvindeide** [comment]
> i.e. change base_dir to be Enspath for example.

Changing `base_dir` to `EnsPath` is probably not a good idea as that will mean the reports end up as (invalid) cases in `storage`.   I have suggested a change in https://github.com/equinor/semeio/pull/333, would that solve your problem? It will still overwrite files if run with the same parameters multiple times. There are of course good and bad aspects of that, what is your experience while running the workflow? @mareco701 and @tralsos?

The change is this:
```
          def _get_output_dir(self):
              res_config = self.ert().resConfig()
              base_dir = Path(res_config.model_config.getEnspath()).parent.absolute()
              sub_dir = str(
                  self.ert().getEnkfFsManager().getCurrentFileSystem().getCaseName()
 
              )
              return os.path.join(
                  base_dir,
                  "reports",
                  Path(res_config.user_config_file).stem,
                  sub_dir,
                  type(self).__name__,
```

So if no `EnsPath` it will be in the config dir under: `reports/<config_name>/<case_name>/<workflow_name>`

**Comment by mareco701** [comment]
Hei, it seems that it is a good way to solve at least one issue which is that you will be able to know to which config file the results in reports are linked (and as you say it would still overwrite files if run from same config). Otherwise I had a workaround which was to adapt/define ENSPATH different from fmu standard. which also only solving the same issue.

**Comment by oyvindeide** [comment]
There are some pros and cons to overwriting, I would personally like for them to overwrite, as I find that it quickly becomes confusing if it does not (we would have to rename existing files with number, or time stamp or the like). What is your opinion?

**Comment by tralsos** [comment]
Would it be possible to let the user define the reports path like we today do for the ENSPATH, LOG_FILE, UPDATE_LOG_PATH and RUNPATH_FILE ? For these the current standard in the projects is to set them to a path that is not linked to the config file, only a defined <CASE_DIR>, e.g:
ENSPATH  ../output/storage/<CASE_DIR>

but could we likewise be possible to allow for setting:
REPORTPATH ../output/reports/<CASE_DIR>

It is more common to change only the case_dir name in the config file and keep the config file name.

Regarding overwriting. I think it makes sense to overwrite when the CASE_DIR is the same. But we need to make sure that when the MISFIT_PREPROCESSOR is run twice in sequence (with different subsets of observations) the second results are appended to the first.  However, appending also to a previous run like we have it today is quite confusing. Not all remember to delete the file first before they make a repeat of a case that they have run before.

**Comment by oyvindeide** [comment]
> Would it be possible to let the user define the reports path like we today do for the ENSPATH, LOG_FILE, UPDATE_LOG_PATH and RUNPATH_FILE ? For these the current standard in the projects is to set them to a path that is not linked to the config file, only a defined <CASE_DIR>, e.g:
> ENSPATH ../output/storage/<CASE_DIR>

Not really possible at the moment, as that would require changes in the current `ert` config, and that is probably more work than it is worth. We can bring the idea into the next `ert` config though.

I suggest we expose the possibility of setting the output directory in the workflow config. So it will not be possible to set it in the `ert` config, but it will be an option when running the workflow config. Does that sound like it would solve the problem?

If the user sets it with an absolute path, we use that path, if they give a relative path, we use the config file as the starting point.

**Comment by tralsos** [comment]
That sounds like a good idea. Will we then be able to pick up e.g. <CASE_DIR> from the ert config file to use it to define a part of the path name. 
e.g. so that we can define the output path to be:
../ouput/reports/<CASE_DIR>/
where CASE_DIR is defined in the ert config file.

**Comment by mareco701** [comment]
I agree that would also give the option to specify the  <ANALYSIS_CASE_NAME> (defined in ERT config) in the path. But  would there be a default report path or it will be a required argument ?

**Comment by oyvindeide** [comment]
> That sounds like a good idea. Will we then be able to pick up e.g. <CASE_DIR> from the ert config file to use it to define a part of the path name.
e.g. so that we can define the output path to be:
../ouput/reports/<CASE_DIR>/
where CASE_DIR is defined in the ert config file.

Definitions are possible to use in the workflow config (but not in the job config in the case of the `MISFIT_PREPROCESSOR` for example).

So for `AHM_ANALYSIS` we can run it with: `AHM_ANALYSIS analysis_case default data_key <CASE_NAME>` and it will use the definition and put it in that folder.

For the `MISFIT_PREPROCESSOR` the only argument is the job config file, and we optionally allow it to run without any arguments. So adding a second argument is not straight forward (we would have to allow 0, 1 or 2 arguments, and if you want to use output directory you would also have to use a config file). We could add an entry to the job config file, and it would put it in that folder, but using definitions is not possible there.

Does that make sense at all? And is it acceptable to not use definitions for the `MISFIT_PREPROCESSOR`? Names arguments are not possible in ert config files, but could be so in the future.

We will have a default location for the reports (I suggest the one I posted previously in this issue), so the user does not have to change it if they dont want to.

**Comment by tralsos** [comment]
I see, so for MISFIT_PREPROCESSOR it would be in this path:
../ouput/reports/<config_name>/<case_name>/<workflow_name>

That should work, and it will be clear with case these reports belong to.

**Comment by oyvindeide** [comment]
I have updated my PR, so if at all possible, would be great if you could test it to make sure it works for you. If you have an environment with `ert` you can: `pip install git+https://github.com/oyvindeide/semeio.git@change_report_dir`. 

For `MISFIT_PREPROCESSOR` it can be configured in the config file under: `reports_directory: some_directory_name`
For `AHM_ANALYSIS` I added it as a workflow argument: `AHM_ANALYSIS analysis_case default data_key <CASE_NAME>` (the fourth argument)

And if not configured, would be great if it is placed where you expect.
