### ISSUE TITLE
Can not raise argparse.ArgumentError without catching outside parsing

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/semeio#34]
The simple `raise argparse.ArgumentError` works as long as you are within the context of parsing. If the exception is raised after the parsing of arguments (e.g. in `gendata_rft`, where we are loading file content after the parsing is completed):

```
(ert_36) [lpha@be-lx923569 norne]$ python /work/GitProjects/semeio/semeio/jobs/scripts/gendata_rft.py -e NORNE_ATW2013 -t gendata_rft_input_files -w gendata_rft_input_files/well_and_time.txt
Traceback (most recent call last):
  File "/work/GitProjects/semeio/semeio/jobs/scripts/gendata_rft.py", line 127, in <module>
    main_entry_point(sys.argv[1:])
  File "/work/GitProjects/semeio/semeio/jobs/scripts/gendata_rft.py", line 110, in main_entry_point
    for wname in well_names
  File "/work/GitProjects/semeio/semeio/jobs/scripts/gendata_rft.py", line 110, in <dictcomp>
    for wname in well_names
  File "/work/venvs/ert_36/lib/python3.6/site-packages/semeio/jobs/rft/trajectory.py", line 98, in load_from_file
    filename=filename
argparse.ArgumentTypeError: Warning: Trajectory file gendata_rft_input_files/B-1AH.txt not found!
```

I think the best way of handling this is to pass the error upwards, preferably by catching the thrown error inside the `main_entry_point` and then calling `parser.error(exception.msg)`

**Comment by oyvindeide** [comment]
Seems like a reasonable approach, something similar is done here: https://github.com/equinor/semeio/blob/66f6ae542c79a2c7ad9b6cadb93a2f39fa66cabe/semeio/jobs/scripts/overburden_timeshift.py#L50

That voids the traceback in the output, while still providing useful feedback to the users.
