### ISSUE TITLE
Remove dependency on setup.py test

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#35]
`python setup.py test` is deprecated due to security concerns, and with it `pytest-runner` which we are using to run tests (https://pypi.org/project/pytest-runner/), we should move to a different way of running tests. Either `pytest` directly or `tox`.

**Comment by markusdregi** [comment]
Interesting! I think this affects quite some of our projects...

**Comment by oyvindeide** [comment]
Yes, added the same issue in `semeio`, but should probably be created other places as well.

**Comment by oyvindeide** [comment]
This has been fixed.
