### ISSUE TITLE
Upgrade semeio to current master will break (clean install works)

### ISSUE THREAD

**Issue by lars-petter-hauge** [equinor/semeio#362]
**Describe the bug**
Given that a version of semeio prior to https://github.com/equinor/semeio/commit/9a01c0adbe514938f464cca475afe98a0f52b8d2 is installed, after the commit mentioned is included, loading configuration jobs in ert will break.

**To Reproduce**
1. `pip install semeio==1.1.5` (or any released version)
2. `pip install semeio#master`
3. Run ert (config irrelevant)

Application will fail with `ValueError: STEA does not end with _CONFIG`

**Expected behavior**
Expect ert to load jobs from semeio

**Additional context**
The issue occur as the job configurations files (https://github.com/equinor/semeio/tree/master/semeio/jobs/config_jobs) are added as data files during `pip install` when running `setuptools.setup`. When upgrading, `setup` will not clean old files and thus they remain. As such both files with and without the suffix are included.

Furthermore it will not be possible to `uninstall` after first installing the upgrade, as the list of installed files will be overwritten, and hence only the newest data files will be removed. The old ones will be listed as "_not to be removed - could have been added manually_".

Unclear how we should handle this.

 - Add a home-made clean up that checks if old files exist and remove if so
 - Revert commit and resign the attempt
 - Give instructions on how to surpass the issue in e.g. README

Personally I would not favour the first. Given that we don't have a large userbase (and for most of our users, we are the ones setting up the environment), it could be acceptable with the last suggestion.

Note: I don't think being less strict in the validation will lead to anything but problems further down the line (as in allow both names to be present. Likely not an issue for linux - although it will be really awkward. osx will work for all new releases) https://github.com/equinor/semeio/blob/63e27ce3f5c0af8ec06a0731c267d306d05ed8d9/semeio/hook_implementations/jobs.py#L11

**Comment by oyvindeide** [comment]
I think this is a wont fix, the solution fairly straight forward, and if we get more reports we add it to the README.
