### ISSUE TITLE
Wrong number of observations with summary observations

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#37]
`CORRELATED_OBSERVATION_SCALING` picks up the wrong number of observations when using `SUMMARY_OBSERVATONS`. The input has x number of observations, but the job reports x * x observations, leading to the wrong scaling factor being calculated.

Data to replicate this problem should be present in:
https://github.com/equinor/libres/tree/master/test-data/local/snake_oil

**Comment by jondequinor** [comment]
In e.g. `test_main_entry_point_summary_data_update` there seems to be 32 observations, and the job reports 122. But this isn't `x^2`.

```
(EnkfObs(valid, len=32) at 0x38d69e0, 32)
Calculation scaling factor, nr of primary components: 1, number of observations: 122
```
How exactly can I reproduce this (`x*x`)?

**Comment by oyvindeide** [comment]
Not quite sure which observation you're looking at, as I can't get any of them to be 32, for example: `measured_data.data.loc["OBS"]["WWCT:OP_2"]._get_label_or_level_values("key_index").unique()` gives length 61, also true for WWCT:OP_1, which seems to correspond with the `*.UNSMRY` file: 

```
In [1]: from ecl.summary import EclSum                                                                   
In [2]: ecl_data = EclSum("EXAMPLE_01_BASE.UNSMRY")  

In [3]: ecl_data["WWCT:OP_2"]                                                                            
Out[3]: EclSumVector(key = WWCT:OP_2, size = 63, unit = )

In [4]: ecl_data["WWCT:OP_1"]                                                                           
Out[4]: EclSumVector(key = WWCT:OP_1, size = 63, unit = )
```
There were a few inactive observations which were removed.
