### ISSUE TITLE
Crash in MISFIT_PREPROCESSOR

### ISSUE THREAD

**Issue by berland** [equinor/semeio#370]
**Describe the bug**
Crash while running the MISFIT_PREPROCESSOR workflow 
```
/prog/res/komodo/2021.11.00-py36-rhel7/root/lib/python3.6/site-packages/semeio/workflows/correlated_observations_scaling/scaled_matrix.py:93: RuntimeWarning: invalid value encountered in subtract
  data_matrix = data_matrix - data_matrix.mean(axis=0)
The script 'MisfitPreprocessorJob' caused an error while running:
On entry to DLASCL parameter number 4 had an illegal valueThe script 'MisfitPreprocessorJob' caused an error while running:
Index contains duplicate entries, cannot reshape
```

**To Reproduce**
Run the command ert workflow misfit_preprocessor `xxxxxxxx_hist_test.ert` in the user provided directory

**Expected behavior**
No crash

**Additional context**
https://equinor.slack.com/archives/CDPJULWR4/p1636415025018700

**Comment by berland** [comment]
Infinite values in column 1.
```
> /private/havb/projects/semeio/semeio/workflows/correlated_observations_scaling/scaled_matrix.py(94)get_nr_primary_components()
-> data_matrix = self.get_data_matrix()
(Pdb) self.get_data_matrix()
array([[       inf, 5.7711589 , 5.83346063, ..., 0.7339083 , 0.55704201,
        0.47497283],
       [       inf, 5.17796528, 5.19280956, ..., 0.67342209, 0.69398402,
        0.77328708],
       [       inf, 5.28730362, 5.28506524, ..., 0.61293492, 0.62551278,
        0.7754112 ],
       ...,
       [       inf, 5.17196006, 5.19280956, ..., 0.91861672, 0.90125105,
        0.92915193],
       [       inf, 5.28730362, 5.28161872, ..., 0.73554343, 0.76429031,
        0.63128485],
       [       inf, 4.6966031 , 4.58756359, ..., 1.16217718, 1.18253514,
        1.08915297]])

```

**Comment by berland** [comment]
The infinity stems from the measured data. My immediate hunch is that 

https://github.com/equinor/ert/blob/main/ert_data/measured.py#L69-L76

should also drop columns with infinity data. Pending access to the scratch disk, I will dig some more.

**Comment by oyvindeide** [comment]
> The infinity stems from the measured data. My immediate hunch is that
> 
> https://github.com/equinor/ert/blob/main/ert_data/measured.py#L69-L76
> 
> should also drop columns with infinity data. Pending access to the scratch disk, I will dig some more.

Sounds reasonable, but would be good to know why the data becomes `inf` in the first place, but suspect that is what you will dig into :)

**Comment by berland** [comment]
The root cause for the crash is that the user has instructed Eclipse100 to take a microsecond timestep. This is not supported by libecl, which makes `welltest_dpds` not work, and `MISFIT_PREPROCESSOR` not work.

**Comment by berland** [comment]
This is a won't-fix, except for fixing the missing newline in the stack-trace.
