### ISSUE TITLE
Jenkins unit-tests hangs when completed

### ISSUE THREAD

**Issue by oysteoh** [equinor/semeio#411]
Sometimes the unit-tests >> semeio is hanging when it seemingly is completed and eventually needs to be aborted by a user to finish. Last 14 days it seems to have happened 4 out of 20 runs approx. 

Example can be found here https://ci.equinor.com/komodo/job/unit-tests/job/semeio/1293/console

**Comment by sondreso** [comment]
Happened again for bleeding (https://ci.equinor.com/komodo/job/unit-tests/job/semeio/1296/console). A bunch of error messages like the one below appears after the test have finished successfully, hinting to what the error might be: 

```
<class 'OSError'>: [Errno 39] Directory not empty: 'missing_rms_input'
  PytestWarning(f"(rm_rf) error removing {path}\n{exctype}: {excvalue}")
/tmp/jenkins-komodo-f_scout_ci/workspace/unit-tests/semeio/test-kenv/root/lib64/python3.6/site-packages/_pytest/pathlib.py:80: PytestWarning: (rm_rf) error removing /tmp/pytest-of-f_scout_ci/garbage-39c22d85-6211-4e38-a5e4-626c669f45e3/test_missing_directory_permiss3
```

**Comment by BjarneHerland** [comment]
@lars-petter-hauge does this relate to what you're currently looking at (the tmpdir-issues)?

**Comment by berland** [comment]
These directories are remnants from running the test https://github.com/equinor/subscript/blob/096a73ad9318ffc474921b9a2a24b52365cb71cc/tests/test_fmu_copy_revision.py#L183

The files left on Jenkins that cannot be deleted might be old (I have no access to check), as earlier implementations of the test did not clean up properly. `chmod` and  `rm` on the test node is needed to clean up manually, and then it would be interesting to see if these warnings can pop up again (but I am not convinced yet that this can cause a test to hang(?))

**Comment by sondreso** [comment]
This issues seems to be resolved now, will reopen if it occurs again
