### ISSUE TITLE
[COS] Improve stdout formatting

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#42]
Correlated Observations scaling

Important information is quickly hidden in and overflow of metadata (when all keys are listed, and the datastructures leak through to the terminal)

**Comment by jondequinor** [comment]
We are currently discussing how to handle output from workflows here: https://github.com/equinor/semeio/pull/66 — this discussion will most likely affect this issue/make it more actionable.

**Comment by markusdregi** [comment]
The output will be structured differently when using the reporter. For now superseded by #112
