### ISSUE TITLE
[COS] Provide `--outfile` option

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#43]
Correlated Observations scaling

Provide output to file in addition to terminal?

**Comment by jondequinor** [comment]
What will go into the file? The terminal output is currently 
```
Calculation scaling factor, nr of primary components: 2, number of observations: 4
Scaling factor calculated from (named_dict(index=None, key='WPR_DIFF_1'),)
Keys: ['WPR_DIFF_1'] scaled with scaling factor: 1.41421356237
Calculation scaling factor, nr of primary components: 2, number of observations: 3
Scaling factor calculated from (named_dict(index=(400, 800, 1200), key='WPR_DIFF_1'),)
Keys: ['WPR_DIFF_1'] scaled with scaling factor: 1.22474487139
```
Should it instead be exported into some portable data format?

**Comment by jondequinor** [comment]
We are currently discussing how to handle output from workflows here: https://github.com/equinor/semeio/pull/66 — this discussion will most likely affect this issue/make it more actionable.

**Comment by markusdregi** [comment]
The output files are dictated by the reporter. Later, the data will be available through storage instead.
