### ISSUE TITLE
[SC] Provide more options to cluster analysis

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#44]
Spearman Correlation.

It is difficult to set default values for thresholds.

The `scipy` functions [`linkage`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.linkage.html) and  [`fcluster`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.cluster.hierarchy.fcluster.html?highlight=fcluster#scipy.cluster.hierarchy.fcluster) are currently given simple defaults. Consider allowing the user to modify the input arguments.

https://github.com/equinor/semeio/blob/2e779f8d4b3c52bafbc519796dbe5f928ea57af7/semeio/jobs/spearman_correlation_job/job.py#L98

**Comment by markusdregi** [comment]
I've tried to make a general discussion on configuration of the correlation jobs in https://github.com/equinor/semeio/issues/67.

**Comment by markusdregi** [comment]
Superseded by #68
