### ISSUE TITLE
[COS] Output singular values

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#45]
Correlated Observations scaling

Users would like output of singular values to stdout

https://github.com/equinor/semeio/blob/2e779f8d4b3c52bafbc519796dbe5f928ea57af7/semeio/jobs/correlated_observations_scaling/scaled_matrix.py#L81

**Comment by jondequinor** [comment]
For what purpose? There's already a bunch of stuff on STDOUT when running workflows. Could this instead be exported via some other, more robust fashion?

**Comment by jondequinor** [comment]
Seems the `s` in the referenced code ( https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.svd.html ) is in the given context, singular values from a PCA analysis.

**Comment by oyvindeide** [comment]
> For what purpose? There's already a bunch of stuff on STDOUT when running workflows. Could this instead be exported via some other, more robust fashion?

Agreed, should be, we´ve talked about the message bus previously, any solution we make should be as easy as possible to integrate into that, when we get to it.

**Comment by jondequinor** [comment]
We are currently discussing how to handle output from workflows here: https://github.com/equinor/semeio/pull/66 — this discussion will most likely affect this issue/make it more actionable.

**Comment by ManInFez** [comment]
Now that the reporter has been merged. The job script should be converted from ErtScript to SemeioScript and use the reporter for exporting data/logging output. 

The single value s, can be logged using the the logger module, which is handled as the Filereporter in the SemeioScript

**Comment by markusdregi** [comment]
Superseeded by #112
