### ISSUE TITLE
[SC] Add option to use only a subset of observations

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#46]
Spearman Correlation.

Allow the user to use only a subset of observations (should likely allow wildcard) when doing the correlation analysis.

Already added in correlation observation scaling:
https://github.com/equinor/semeio/blob/2e93d4011e4a9ace5bb0ff423796d07cb565f307/semeio/jobs/correlated_observations_scaling/job.py#L85

**Comment by markusdregi** [comment]
I've tried to make a general discussion on configuration of the correlation jobs in https://github.com/equinor/semeio/issues/67.

**Comment by markusdregi** [comment]
#68 exposed this for the entire pipeline, #108 should make this available for SC as well.
