### ISSUE TITLE
Misfit preprocessor test question

### ISSUE THREAD

**Issue by dafeda** [equinor/semeio#465]
`test_misfit_preprocessor_n_polynomials` with 2 polynomials does clustering on data that look something like this:

![Screenshot 2022-10-10 at 09 53 14](https://user-images.githubusercontent.com/45088507/194820353-407600f0-5e59-490e-be38-3939c40df8b2.png)

The settings for the clustering are the following:

```
'method':
'average'
'metric':
'euclidean'
'depth':
2
'criterion':
'maxclust'
'threshold':
3
len():
5
```

`threshold`: 3 is the result of PCA with a pca-threshold of 0.99.

After `flcuster` has been run, we get this:

![Screenshot 2022-10-10 at 09 55 46](https://user-images.githubusercontent.com/45088507/194820789-14a2b925-7e79-42a5-a862-37d9e877e05c.png)

How do I interpret this?

**Comment by berland** [comment]
Is there a resolution to this, or should this be kept open?
