### ISSUE TITLE
[SC] Possibly dump correlation analysis to csv

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#48]
Allow the user to dump the correlation data

https://github.com/equinor/semeio/blob/2e779f8d4b3c52bafbc519796dbe5f928ea57af7/semeio/jobs/spearman_correlation_job/job.py#L29

**Comment by jondequinor** [comment]
We are currently discussing how to handle output from workflows here: https://github.com/equinor/semeio/pull/66 — this discussion will most likely affect this issue/make it more actionable.

**Comment by markusdregi** [comment]
Superseded by #24
