### ISSUE TITLE
[SC] Provide `--outfile` option

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#49]
Spearman Correlation

Provide output to file in addition to terminal?

**Comment by jondequinor** [comment]
What is the output?

**Comment by markusdregi** [comment]
Probably what is currently printed to the terminal?

**Comment by jondequinor** [comment]
The clustering? Why would they want that? At least in it's current form, where it not parseable (it's natural language). Would it make sense to instead add an `--export-csv=foo.csv` where the clusters are in the CSV format? Then it at least a bit portable.

**Comment by jondequinor** [comment]
We are currently discussing how to handle output from workflows here: https://github.com/equinor/semeio/pull/66 — this discussion will most likely affect this issue/make it more actionable.

**Comment by ManInFez** [comment]
Now that the reporter has been merged. The job script should be converted from ErtScript to SemeioScript and use the reporter for exporting data/logging output.

**Comment by markusdregi** [comment]
The output location is dictated by the reporter. Will in first iteration be files, but will later be exposed through storage instead.
