### ISSUE TITLE
AHM_ANALYSIS: Workflow fails if all observations are deactivated during update

### ISSUE THREAD

**Issue by oyvindeide** [equinor/semeio#498]
**Describe the bug**
Run the AHM_ANALYSIS report with a case where all the observations in a group are deactivated because of outlier detection. The analysis will fail, causing the whole job to fail. Instead we should catch the exception and make a reasonable update report instead, which highlights which observations are excluded.

**Comment by oddvarlia** [comment]
This error also occurs when running the LOCALISATION_JOB. The localisation code should check if some observations are active before creating a ministep and just skip the ministep (not create it) if all observations are deactivated, BUT should report this with a warning.
