### ISSUE TITLE
filter_ensemble_mean_obs from MeasuredData in SC

### ISSUE THREAD

**Issue by jondequinor** [equinor/semeio#63]
From https://github.com/equinor/semeio/pull/62 : 

> I was also thinking that we should add filter_ensemble_mean_obs from MeasuredData, as now we´re doing that in the scaling, and also in the algorithm, so those observations will never be used

**Comment by jondequinor** [comment]
What will the alpha be here? @oyvindeide

**Comment by jondequinor** [comment]
Can I assume `3.0`i.e. the default?

**Comment by oyvindeide** [comment]
Yes, that´s the default in `libres`,  so should stick with that. Can we think of a better way to configure this so that it´s consistent between different jobs?

**Comment by jondequinor** [comment]
Maybe we could discuss it in https://github.com/equinor/semeio/issues/47

**Comment by markusdregi** [comment]
This will be resolved by #105
