### ISSUE TITLE
[COS] dump analysis artifacts in data format that preserves semantics

### ISSUE THREAD

**Issue by jondequinor** [equinor/semeio#64]
https://github.com/equinor/semeio/issues/45
https://github.com/equinor/semeio/issues/43
https://github.com/equinor/semeio/issues/42

could all be solved by simply dumping the appropriate data from a COS run.

**Comment by jondequinor** [comment]
We are currently discussing how to handle output from workflows here: https://github.com/equinor/semeio/pull/66 — this discussion will most likely affect this issue/make it more actionable.

**Comment by markusdregi** [comment]
Resolved by the reporter discussion
