### ISSUE TITLE
Validate DESIGN_KW configuration at start up instead of when running forward model

### ISSUE THREAD

**Issue by eivindjahren** [equinor/semeio#641]
The following list of errors can happen on running the forward model step. It should be validated at startup.

* `WARNING - Key(s) [...] can only be used with prefix.`
* `ERROR - <...> not found in design matrix`
* `design_kw: error: argument templatefile: /..../input/templates/plate.tmpl is not an existing file!`
* `MULTFLT is defined multiple times`

Also the following uncaught exceptions from `extract_key_value` can occurr which should be result in a better error message at startup.

```
File ".../python3.8/site-packages/semeio/forward_models/design_kw/design_kw.py", line 113, in extract_key_value
line_parts = shlex.split(line)
File "/usr/lib64/python3.8/shlex.py", line 311, in split
return list(lex)
File "/usr/lib64/python3.8/shlex.py", line 300, in __next__
token = self.get_token()
File "/usr/lib64/python3.8/shlex.py", line 109, in get_token
raw = self.read_token()
File "/usr/lib64/python3.8/shlex.py", line 191, in read_token
raise ValueError("No closing quotation")
ValueError: No closing quotation
```
```
File ".../python3.8/site-packages/semeio/forward_models/design_kw/design_kw.py", line 135, in extract_key_value
raise ValueError("\n".join(errors))
ValueError: No value found in line ...
```

**Comment by jonathan-eq** [comment]
@eivindjahren Should this be an error, stopping the user from proceeding? It is currently only a warning. `WARNING - Key(s) [...] can only be used with prefix`

**Comment by eivindjahren** [comment]
> @eivindjahren Should this be an error, stopping the user from proceeding? It is currently only a warning. `WARNING - Key(s) [...] can only be used with prefix`

That is indicating that something might be wrong with the key so I guess its a warning. Generally, we haven't really looked into what is possible as some of these values may be generated on the compute node.

**Comment by eivindjahren** [comment]
It could be that `<template_file>` is generated by a previous forward model step. However, we believe it is unlikely, but we need to check that assumption. Propose the following steps:

* Generate warnings from validation with an option to turn the validation off `FORWARD_MODEL DESIGN_KW(..., <VALIDATE>=false)`.
* Log when these warnings are shown (already done in ert)
* Turn the warning into an error if this warning is shown very seldom or never with an option to turn it off `FORWARD_MODEL DESIGN_KW(..., <VALIDATE>=false)`.
