### ISSUE TITLE
Remove libres as a dependency

### ISSUE THREAD

**Issue by markusdregi** [equinor/semeio#69]
The jobs related to scaling observations has a quite hard dependency on libres. After https://github.com/equinor/semeio/issues/67 has been resolved and a standardised pipeline has been established we should be able to get rid of libres as a dependency of semeio.

**Comment by oyvindeide** [comment]
While I agree that that is definitely the right direction to move, currently the scaling jobs are using `ErtScript`which resides in libres, and while the currently implementation basically just passes on `EnkFMain`, the implementation could be changed (and moved to `ert`) to a plugin system where we can expose a more sane API, for example serving up observations, and allowing the user to set certain variables, for example the scaling factor. That would free semeio of libres dependency and be more data driven and less knowledgeable about the inner workings of libres.

**Comment by oyvindeide** [comment]
We are bound to this dependency as long as the api for workflows does not change. I will close this issue as it is not actionable, but I think we both agree that as soon as this is possible we will create an action to update to a new api.
